image: schteeben/anu:ass03

stages:
    - integrity
    - anti-cheat
    - build
    - test
    - deploy
    
before_script:
    - ssh-keyscan gitlab.cecs.anu.edu.au >> ~/.ssh/known_hosts
    
Integrity:
    stage: integrity
    tags:
        - comp1100
    script:
        - sh /Scripts/IntegrityCheck.sh
    
Hacks:
    stage: anti-cheat
    tags:
        - comp1100
    script:
        - sh /Scripts/CheatingCheck.sh
    
Compilation:
    stage: build
    tags:
        - comp1100
    script:
        - stack setup
        - stack build
        
Runtime:
    stage: test
    tags:
        - comp1100
    script:
        - sh /Scripts/RunGame.sh
        
Submission: 
    stage: deploy
    tags:
        - comp1100
    script:
        - sh /Scripts/Submit.sh